name = "followage"
main = "dist/index.mjs"

logpush = true
workers_dev = false
account_id = "ae21073ba569d28e3fddb8cf9e3f0852"

compatibility_date = "2023-09-29"
compatibility_flags = []

routes = [
	{ pattern = "twitchcommands.matthewgrima.com", custom_domain = true }
]

kv_namespaces = [
	{ binding = "KV", id = "af9283071986403bb1026c0112554503" }
]

[durable_objects]
bindings = [
	{ name = "AuthTokens", class_name = "AuthTokens" }
]

[[migrations]]
tag = "v1"
new_classes = ["AuthTokens"]

[[analytics_engine_datasets]]
binding = "FollowageApp"

[triggers]
crons = ["0 4 * * *"]

[vars]
WEBHOOK_BASE_URL = "https://commands.garretcharp.com"

[build]
command = "npm run build"
